In [3]:
from keras.applications.vgg16 import VGG16
import keras

In [6]:
vgg16 = keras.applications.vgg16.VGG16(
            include_top=False, weights='imagenet', input_tensor=None, input_shape=(512, 512, 3))

In [7]:
vgg16.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 512, 512, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 512, 512, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 512, 512, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 256, 256, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 256, 256, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 256, 256, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 128, 128, 128)     0         
__________

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.append(np.expand_dims(a, axis=2), np.expand_dims(b, axis=2), axis=2)
print c
d = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
print np.concatenate(d, axis=1)
#print (*(1,2,3), 4)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[1 2 5 6]
 [3 4 7 8]]


In [8]:
a = np.zeros((3, 4, 3))
b = np.ones((4, 3, 3))
for i in range(3):
    for j in range(4):
        for k in range(3):
            a[i, j, k] = i + j + k
for i in range(4):
    for j in range(3):
        for k in range(3):
            b[i, j, k] = -(i + j + k)
print a
print b

[[[ 0.  1.  2.]
  [ 1.  2.  3.]
  [ 2.  3.  4.]
  [ 3.  4.  5.]]

 [[ 1.  2.  3.]
  [ 2.  3.  4.]
  [ 3.  4.  5.]
  [ 4.  5.  6.]]

 [[ 2.  3.  4.]
  [ 3.  4.  5.]
  [ 4.  5.  6.]
  [ 5.  6.  7.]]]
[[[ 0. -1. -2.]
  [-1. -2. -3.]
  [-2. -3. -4.]]

 [[-1. -2. -3.]
  [-2. -3. -4.]
  [-3. -4. -5.]]

 [[-2. -3. -4.]
  [-3. -4. -5.]
  [-4. -5. -6.]]

 [[-3. -4. -5.]
  [-4. -5. -6.]
  [-5. -6. -7.]]]


In [17]:
print np.meshgrid(np.arange(3), np.arange(3))
print a[np.meshgrid(np.arange(3), np.arange(3))]
a[np.meshgrid(np.arange(3), np.arange(3))] = b[np.meshgrid(np.arange(3), np.arange(3))]
print a

[array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]]), array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])]
[[[ 0.  1.  2.]
  [ 1.  2.  3.]
  [ 2.  3.  4.]]

 [[ 1.  2.  3.]
  [ 2.  3.  4.]
  [ 3.  4.  5.]]

 [[ 2.  3.  4.]
  [ 3.  4.  5.]
  [ 4.  5.  6.]]]
[[[ 0. -1. -2.]
  [-1. -2. -3.]
  [-2. -3. -4.]
  [ 3.  4.  5.]]

 [[-1. -2. -3.]
  [-2. -3. -4.]
  [-3. -4. -5.]
  [ 4.  5.  6.]]

 [[-2. -3. -4.]
  [-3. -4. -5.]
  [-4. -5. -6.]
  [ 5.  6.  7.]]]


In [20]:
print a[2:100, 2:100, :]

[[[-4. -5. -6.]
  [ 5.  6.  7.]]]
