In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.append(np.expand_dims(a, axis=2), np.expand_dims(b, axis=2), axis=2)
print c
d = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
print np.concatenate(d, axis=1)
#print (*(1,2,3), 4)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[1 2 5 6]
 [3 4 7 8]]
