In [3]:
from keras.applications.vgg16 import VGG16
import keras

In [8]:
vgg16 = keras.applications.vgg16.VGG16(
            include_top=False, weights='imagenet', input_tensor=None, input_shape=(64, 64, 3))

In [9]:
vgg16.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 64, 64, 3)         0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 64, 64, 64)        1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 64, 64, 64)        36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 32, 32, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 32, 32, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 32, 32, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 16, 16, 128)       0         
__________

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.append(np.expand_dims(a, axis=2), np.expand_dims(b, axis=2), axis=2)
print c
d = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
print np.concatenate(d, axis=1)
#print (*(1,2,3), 4)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[1 2 5 6]
 [3 4 7 8]]
